<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/python_fundamentos/src/08_modules_to_data_analysis/01_creating_arrays_with_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

website: [numpy.org](https://numpy.org)

To update NumPy, open the terminal and type: `pip install numpy -U`

In [0]:
# Importing NumPy
import numpy as np

In [3]:
# Check version
np.__version__

'1.16.5'

## Creating Arrays

In [4]:
# Help
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [0]:
# Create an array from a list
vector1 = np.array([0,1,2,3,4,5,6,7,8,9])

In [6]:
print(vector1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# A object with type ndarray is a recipient multidimensional with itens of same type and length
type(vector1)

numpy.ndarray

In [12]:
# Using methods of NumPy - Accumulated Sum
vector1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [15]:
# Arrays allow values of same type, a error is thrown when we inserting a string into vector1
vector1[0] = 'New Element'

ValueError: ignored

In [16]:
# Print the dimension of array, (10,) meaning that vector1 has one dimension
print(vector1.shape)

(10,)


## Functions NumPy

In [0]:
# The function arange() creates a vector containing a arithmetic from a interval - start, stop, step
vector2 = np.arange(0., 4.5, .5)

In [18]:
print(vector2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [19]:
# Check object type
type(vector2)

numpy.ndarray

In [20]:
# Check how many dimensions
print(vector2.shape)

(9,)


In [21]:
# Creating an array with zeros() function - This is useful to initialize the weights in a deep neural network
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# Return .1 in positions of diagonal in matrix
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# The values passed as parameter, form a diagonal
d = np.diag(np.array([1,2,3,4]))
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [26]:
# Create a array with complex numbers
b = np.array([1+2j, 3+4j, 5+6*1j])
print(b)

[1.+2.j 3.+4.j 5.+6.j]


In [28]:
# Arrays with boolean values
b = np.array([True, False, False, True])
print(b)

[ True False False  True]


In [29]:
# Arrays with strings
c = np.array(['python', 'big data', 'NumPy'])
print(c)

['python' 'big data' 'NumPy']


In [31]:
# The linspace() method (linearly spaced vector) returns a number of values equally distribuited in a specified interval
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [32]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [34]:
# How to make a interval with logspace()
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


## Matrix