<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/src/06_Modulos_Analise_de_Dados/01_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

www.numpy.org

To update NumPy package: `pip install numpy -U`

In [0]:
# Import NumPy package
import numpy as np

In [6]:
# Check version
np.__version__

'1.17.4'

## Making Arrays

In [8]:
# Help to array function
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}

In [10]:
# Making an array from a list
vec1 = np.array([0,1,2,3,4,5,6,7,8,9])

print(vec1)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
type(vec1)

numpy.ndarray

In [13]:
# How to use the methods of arrays, for instance, .cumsum()
vec1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [16]:
# Print the elements by index
print(vec1[4])

4


In [18]:
# Change an element by index
vec1[0]=100

print(vec1)

[100   1   2   3   4   5   6   7   8   9]


In [19]:
# We can't change/add an element of another type
vec1[0] = 'string'


ValueError: ignored

In [22]:
# Check the dimension of an array
print(vec1.shape)

(10,)
