<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/src/06_Modulos_Analise_de_Dados/02_NumPy_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy Functions

In [0]:
# Import libraries
import numpy as np

In [0]:
# The function .arange() creates a vector that contains an arithmetic progression from a interval.
# Example: np.arange(start, stop, step)

vec1 = np.arange(0.,4.5, .5)

print(vec1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [0]:
# Check the type of object
type(vec1)

numpy.ndarray

In [0]:
# Check the type of data in the object
print(vec1.dtype)

float64


In [0]:
# Create a new vector
vec2 = np.arange(1,10,0.25)

print(vec2)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [6]:
# Create a array filled with zeros, usefull to start a list of weights to train a deeplearning model
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# Create a matrix (3x3), filled with 1 in the main diagonal
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Create a matrix and pass the number of the main diagonal
print(np.diag(np.array([1,2,3,4])))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [11]:
# Array with complex numbers
print(np.array([1+2j, 3+4j, 5+6*1j]))

[1.+2.j 3.+4.j 5.+6.j]


In [13]:
# Array with boolean values
arr = np.array([True, False, False, True])

arr

array([ True, False, False,  True])

In [17]:
# Array with strings
print(np.array(['Python', 'R', 'Julia']))

['Python' 'R' 'Julia']


In [19]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [16]:
# The linspace method (linearly Spaced Vector) returns a number of 
# values equally distribuited in a specific range
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [23]:
np.logspace(0,5,10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])