<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/src/06_Modulos_Analise_de_Dados/03_NumPy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating Matrices

In [0]:
# Import Numpy
import numpy as np

In [0]:
# Create a simple matrix
mtx = np.array([[1,2,3],[4,5,6]])

print(mtx)

[[1 2 3]
 [4 5 6]]


In [0]:
# Show shape
print(mtx.shape)

(2, 3)


In [0]:
# Initialize a matrix (2,3) filled with numbers 1
mtx1 = np.ones((2,3))

print(mtx1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [0]:
# Create a matrix from a list of lists
list = [[13,81,22],[0,34,59],[21,48,94]]

In [0]:
# The matrix() method creates a matrix from a list in sequence
mtx2 = np.matrix(list)

mtx2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [0]:
type(mtx2)

numpy.matrix

In [0]:
# Show matrix shape
np.shape(mtx2)

(3, 3)

In [0]:
# Show matrix size
np.size(mtx2)

9

In [0]:
# Show matrix type
mtx2.dtype

dtype('int64')

In [0]:
# Show lenght of items
mtx2.itemsize

8

In [0]:
# Show matrix bytes
mtx2.nbytes

72

In [0]:
# Printing a specific value using slice notation
# Remember: The indexing in Python starts in 0
# row x col
print(mtx2[2,1])

48


In [0]:
# Changing a value
mtx2[0,2] = 100

mtx2

matrix([[ 13,  81, 100],
        [  0,  34,  59],
        [ 21,  48,  94]])

In [0]:
# By default, NumPy decides the data type for values
# We can declare the specific data type we want
mtx3 = np.array([1,2], dtype=np.float64)

mtx3

array([1., 2.])

In [0]:
print(mtx3.dtype)

float64


In [0]:
# Create a matrix with specific data type
mtx4 = np.array([[24,36],[40,46],[80,29]],dtype=float)

mtx4

array([[24., 36.],
       [40., 46.],
       [80., 29.]])

In [0]:
# Show number of dimensions
mtx4.ndim

2

In [0]:
# Show value of row 1 and column 1
mtx4[1,1]

46.0

In [0]:
# Change a value
mtx4[2,1] = 300

mtx4

array([[ 24.,  36.],
       [ 40.,  46.],
       [ 80., 300.]])