<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/src/06_Modulos_Analise_de_Dados/06_NumPy_Slicing_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Other Operations with Arrays

In [0]:
# Import libraries
import numpy as np

In [4]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [5]:
# Slicing the second row and the second column
a[1,1]

1

In [7]:
# Slicing the second row
a[1]

array([0, 1, 0])

In [9]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# [start:end:step]
b[2:9:3]

array([2, 5, 8])

In [12]:
# Comparing if two arrays are equal
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
a == b

array([False,  True, False,  True])

In [13]:
np.array_equal(a,b)

False

In [14]:
# Return min and max values from an array
a.min()

1

In [15]:
a.max()

4

In [16]:
# With NumPy, is possible to add values for each element of an array
np.array([1,2,3]) + 1.5

array([2.5, 3.5, 4.5])

In [17]:
# Arounding elements
a = np.array([1.2,1.5,1.6,2.5,3.5,4.5])
a

array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [18]:
np.around(a)

array([1., 2., 2., 2., 4., 4.])

In [20]:
# Copy an array
B = np.array([2,4,5,6])
C = B.flatten()
C

array([2, 4, 5, 6])

In [22]:
# Adding dimensions to an array, humans can abstract up to 4 dimensions at most
v = np.array([2,4,5])
v[ :, np.newaxis], v[ :,np.newaxis].shape, v[np.newaxis,:].shape

(array([[2],
        [4],
        [5]]), (3, 1), (1, 3))

In [23]:
# Repeating each element
np.repeat(v,3)

array([2, 2, 2, 4, 4, 4, 5, 5, 5])

In [24]:
# Repeating all elements 3 times
np.tile(v,3)

array([2, 4, 5, 2, 4, 5, 2, 4, 5])

In [25]:
# Concating arrays
w = np.array([5,2,7])

np.concatenate((v,w), axis=0)

array([2, 4, 5, 5, 2, 7])

In [26]:
# Coping an array
r = np.copy(v)
r

array([2, 4, 5])