<a href="https://colab.research.google.com/github/ralsouza/python_fundamentos/blob/master/src/06_Modulos_Analise_de_Dados/Exercicios_capitulo_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercícios Sobre Módulos Python Para Análise de Dados

**ATENÇÃO**

**Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!**

Exercícios:

[DSA-Python-Cap08-Exercicios.ipynb](https://github.com/ralsouza/Python_Data_Analysis/blob/master/Cap08/Notebooks/DSA-Python-Cap08-Exercicios.ipynb)

Solução:

[DSA-Python-Cap08-Exercicios-Solucao.ipynb](https://github.com/ralsouza/Python_Data_Analysis/blob/master/Cap08/Notebooks/DSA-Python-Cap08-Exercicios-Solucao.ipynb)

## Exercício 1
Crie um array NumPy com 1.000.000 e uma lista com 1.000.000.

Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).

Qual objeto oferece melhor performance, array NumPy ou lista?

In [0]:
import numpy as np

In [0]:
np_arr = np.arange(1000000)
bt_lst = list(range(1000000))

In [0]:
# Time to process NumPy Array
%time for _ in range(10): np_arr2 = np_arr * 2

CPU times: user 16.6 ms, sys: 8.16 ms, total: 24.8 ms
Wall time: 28.9 ms


In [0]:
# Time to process a list
%time for _ in range(10): bt_lst2 = [i * 2 for i in bt_lst]

CPU times: user 655 ms, sys: 199 ms, total: 854 ms
Wall time: 856 ms


## Exercício 2
Crie um array de 10 elementos

Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5:8] = 0
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

## Exercício 3
Crie um array de 3 dimensões e imprima a dimensão 1

In [0]:
# Create an array 3x3
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
# Print the dimension 1
x[0]

array([0, 1, 2])

## Exercício 4
1.   Crie uma matriz 3x3;
2.   Imprima os elementos da terceira linha da matriz;
3.   Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas.

`numpy.matrix`: It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.

[Source: numpy.matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html)

In [0]:
# Create a matrix
y = np.arange(9).reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
# Print the thrird row of matrix
y[2]

array([6, 7, 8])

In [0]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas.
y[:2,1:]

array([[1, 2],
       [4, 5]])

## Exercício 5
Calcule a transposta(pivot) da matriz abaixo


In [0]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## Exercício 6
Considere os 3 arrays abaixo

Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.

In [0]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [0]:
help(enumerate)

In [0]:
# Test enumerate
for idx, value in enumerate(cond,start=1):
  print('Index: {}, Value: {}'.format(idx,value))

Index: 1, Value: True
Index: 2, Value: False
Index: 3, Value: True
Index: 4, Value: True
Index: 5, Value: False


In [0]:
for idx, value in enumerate(cond):
  if cond[idx] == True:
    print(xarr[idx])
    
  if cond[idx] == False:
    print(yarr[idx])

1.1
2.2
1.3
1.4
2.5


In [0]:
list(zip(xarr,yarr,cond))

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [0]:
# https://amir.rachum.com/blog/2012/07/14/double-iteration-in-list-comprehension/

[(x,y,c) for x,y,c in zip(xarr,yarr,cond)]

[(1.1, 2.1, True),
 (1.2, 2.2, False),
 (1.3, 2.3, True),
 (1.4, 2.4, True),
 (1.5, 2.5, False)]

In [0]:
# Ternary Operator: [on_true] if [expression] else [on_false] 
# https://www.geeksforgeeks.org/ternary-operator-in-python/

# 1.1 if True else 2.1
1.1 if False else 2.1

2.1

In [0]:
# Ternary Operator inside a list comprehension
# But, this has multiple problems. First, it will not be very fast for large 
# arrays (because the work is being done in pure Python). Secondly, it will not 
# work with multidimensional arrays. 
[(x if c else y) 
 for x, y, c in zip(xarr, yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [0]:
# With numpy

.where() we can write this very concisely: numpy.where(condition[, x, y])
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html

np.where(cond,xarr,yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

## Exercício 7
Crie um array A com 10 elementos e salve o array em disco com a extensão npy

Depois carregue o array do disco no array B

In [2]:
# numpy.save()
# This function is used to store the input array in a disk file with npy extension(.npy)
# https://www.geeksforgeeks.org/numpy-save/

A = np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# Save the array in the disk
np.save('my_array', A)

In [9]:
# Load the array saved in the disk
B = np.load('my_array.npy')
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercício 8
Considerando a série abaixo, imprima os valores únicos na série

In [0]:
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [12]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.unique.html
print(pd.Series.unique(obj))

['c' 'a' 'd' 'b']


In [15]:
obj_unique = obj.unique()
print(obj_unique)

['c' 'a' 'd' 'b']


## Exercício 9
Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.

In [89]:
import requests
from pandas.io.json import json_normalize
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

200

In [0]:
# Transform the response in JSON files
data = resp.json()
data

In [0]:
df_data = pd.DataFrame.from_dict(data,orient='columns')
df_data.head(3)

In [88]:
# Selecting some columns
df_data[['id','number','title','state']]

id  number                                              title state
0   570863211   32252  (wip) BUG: itertuples was retuning empty list ...  open
1   570858535   32251  pandas.tseries.offsets.CustomBusinessDay apply...  open
2   570851428   32250        TST: method-speciifc file for select_dtypes  open
3   570847545   32248         REF: method-specific file for to_timestamp  open
4   570795665   32247  REF: simplify IntervalIndex/IntervalArray _sha...  open
5   570782807   32246                          web site unwanted message  open
6   570751816   32244               CLN: simplify+annotate _shallow_copy  open
7   570746888   32243                  Convert style object to DataFrame  open
8   570732480   32242  BUG: Fixed bug, where pandas._libs.lib.maybe_c...  open
9   570671758   32240  NamedAgg with as_index= False drops aggregated...  open
10  570559679   32238                               read_excel with xlsb  open
11  570513038   32237          travis: enable bionic & multi-cpu testing  open
12  570501889   32236  Added message to pytest raises for test_constr...  open
13  570462317   32235                 Fix exception causes in 14 modules  open
14  570381519   32234  Using scipy's entropy function with "string" d...  open
15  570302383   32233  [FEATURE] Ability to pass regex module flags i...  open
16  570292846   32232              use ExtensionIndex._concat_same_dtype  open
17  570172852   32224                   PERF: lazify consolidation check  open
18  570141319   32223  BUG: Fix DateFrameGroupBy.mean error for Int64...  open
19  570138111   32222         BUG: the sample skewness is wrong computed  open
20  569975481   32220           CI: value_counts tests failing sometimes  open
21  569949721   32219  calling `mean` on a `DataFrameGroupBy` with `I...  open
22  569821312   32218  Inconsistent behavior when DataFrame with stri...  open
23  569592189   32215  REF: include CategoricalIndex in index_cahced ...  open
24  569586517   32214           BUG: Cast pd.NA to pd.NaT in to_datetime  open
25  569586193   32213         pandas.to_datetime raises when given pd.NA  open
26  569573673   32212                        DOC: DataFrame.ewm clean-up  open
27  569572927   32211  CLN/REF: Split up / clean Categorical construc...  open
28  569559947   32209        CLN: Use defaultdict for minor optimization  open
29  569543306   32207                     read_excel loses spaces on ods  open

# Exercício 10

In [0]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""
con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [0]:
data = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [92]:
cursor = con.execute('select * from teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Norte', 1.25, 6),
 ('Recife', 'Pernambuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [93]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5